--- #YAML:1.0
name:                Dotiac-addon-unparsed
version:             0.2
abstract: |-
  Work with raw Django Template Code
license:             MIT
author:              
  - Marc Lucksch
distribution_type:   module
requires:     
    Dotiac::DTL: 0.2
build_requires:
    Test::More:                      0
    Test::Pod:                       0
provides:
   Dotiac::DTL::Addon::unparsed:
     file: lib/Dotiac/DTL/Addon/unparsed.pm
     version: 0.2
   Dotiac::DTL::Tag::unparsed:
     file: lib/Dotiac/DTL/Tag/unparsed.pm
     version: 0.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
